services:
  academicmanagement.api:
    container_name: academicmanagement.api
    build:
      context: .
      dockerfile: AcademicManagement.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - academicmanagement.database
  academicmanagement.database:
    image: postgres:latest
    container_name: academicmanagement.database
    environment:
      - POSTGRES_DB=acad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/academicmanagement-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
