[build]
builder = "dockerfile"
dockerfilePath = "./AcademicManagement.Api/Dockerfile"

[deploy]
startCommand = "./AcademicManagement.Api"
restartPolicyType = "always"
healthcheckPath = "health"