[build]
builder = "dockerfile"
dockerfilePath = "./AcademicManagement.Api/Dockerfile.prod"

[deploy]
startCommand = "./AcademicManagement.Api.dll"
restartPolicyType = "always"
healthcheckPath = "health"